### PR TITLE
Chore: use GitHub actions

### PR DESCRIPTION
**Pull request by fahchen**
fix https://github.com/tessi/wasmex/issues/317

The successful runs:
- Elixir CI: https://github.com/fahchen/wasmex/actions/runs/2040577753
- Rust CI: https://github.com/fahchen/wasmex/actions/runs/2040577751

### CODE REVIEW

**Comment by fahchen** [comment]
In another [branch](https://github.com/fahchen/wasmex/tree/chore/compatibility-elixir-test), I do the following changes as below, could I introduce these changes into this PR too ?
1. changed the elixir requirement to `~> 1.10` at https://github.com/fahchen/wasmex/commit/11a24f646c3c0e4ab751b8a1d388954098045f09.
1. added an elixir compatibility tests, and the successful run is https://github.com/fahchen/wasmex/runs/5694280106?check_suite_focus=true .
1. We could support `elixir 1.9`, if we remove `is_map_key/2` that was added since `1.10.0`.

**Comment by tessi** [comment]
@fahchen 😍 thanks a lot for taking this on! I didn't have time to look at the changes (hope to get to a review this weekend) but needed to tell you how much I love that you stepped up and did the work! 💪

**Comment by tessi** [comment]
> In another [branch](https://github.com/fahchen/wasmex/tree/chore/compatibility-elixir-test), I do the following changes as below, could I introduce these changes into this PR too ?
> 
> 1. changed the elixir requirement to `~> 1.10` at [fahchen@11a24f6](https://github.com/fahchen/wasmex/commit/11a24f646c3c0e4ab751b8a1d388954098045f09).
> 2. added an elixir compatibility tests, and the successful run is https://github.com/fahchen/wasmex/runs/5694280106?check_suite_focus=true .
> 3. We could support `elixir 1.9`, if we remove `is_map_key/2` that was added since `1.10.0`.

I love what you did here, but let's keep these changes out of this PR. I really like 1. in combination with 2. I personally always try to avoid forcing developers to test on older elixir versions, but if we can make CI do that for us it's great!

Since we're already requiring 1.13, I see no need to be compatible with 1.9 too. So I'd say we don't need to implement 3.

**Review by tessi — APPROVED** [review]
@fahchen you did an awesome job here!

❤️ 💜 💛 💚 💙

**Comment by tessi** [comment]
I'll merge this PR to unblock your other tasks 🤹

**Comment by fahchen** [comment]
> @fahchen you did an awesome job here!
> 
> ❤️ 💜 💛 💚 💙

Thanks for your hard work at this repo, that's help us a lot.

**Pull request merged**
